app/order/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField

app/order/__init__.py
from flask import Blueprint

bp = Blueprint("order", __name__)

from . import routes

app/order/routes.py
from . import bp
from flask import render_template, request, redirect, url_for
from app.models import CartItem
from app import db


@bp.route("/cart")
def shopping_cart():
    cart_id = request.cookies.get("cart")
    cart_items = CartItem.query.filter_by(cart_id=cart_id).all()
    return render_template("order/shopping_cart.html", title="Shopping Cart", items=cart_items)


@bp.route("/add-to-bag", methods=["POST"])
def add_to_bag():
    cart_id = request.cookies.get("cart")
    form = request.form
    product_id = form.get("product_id")
    quantity = form.get("quantity")
    cart_item = CartItem.query.filter_by(cart_id=cart_id, product_id=product_id).first()
    prev_url = request.referrer
    if not cart_item:
        cart_item = CartItem(cart_id=cart_id, product_id=product_id, quantity=quantity)
        db.session.add(cart_item)
    else:
        cart_item.quantity += int(quantity)
    db.session.commit()
    return redirect(prev_url)


@bp.route("/remove/<product_id>")
def remove_item(product_id):
    cart_id = request.cookies.get("cart")
    cart_item = CartItem.query.filter_by(cart_id=cart_id, product_id=product_id).first()
    if cart_item:
        db.session.delete(cart_item)
        db.session.commit()
        return redirect(url_for("order.shopping_cart"))
    return redirect(url_for("order.shopping_cart"))


@bp.route("/checkout")
def checkout():
    return render_template("order/checkout.html", title="Checkout")

app/templates/order/checkout.html
{% extends "base.html" %}

{% block app_content %}
<div>
    <p>Implement later</p>
</div>
{% endblock %}

app/templates/order/shopping_cart.html
{% extends "base.html" %}

{% block app_content %}
{% if items %}
<table class="table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% set total = {"total": 0} %}
        {% for item in items %}
        {% set amount = item.quantity*item.product.price %}
        {% if total.update({"total": total.total + amount }) %} {% endif %}
        <tr>
            <td> 
                <p style="font-weight: bold">{{ item.product.name }}</p>
                <p>{{ item.product.size }} US / {{ item.product.color }}</p>
                <p style="font-weight: bold">${{ item.product.price }}</p>
                <small>
                    <a href="{{ url_for('order.remove_item', product_id=item.product.id) }}">Remove</a>
                </small>
            </td>
            <td>{{ item.quantity }}</td>
            
            <td style="font-weight: bold">${{ amount }}</td>
        </tr>
        {% endfor %}
    </tbody> 
</table>
<div>
    <p style="font-weight: bold">Grand Total: ${{ total.total }} </p>
    <a class="button button-md" href="{{ url_for('order.checkout') }}">Checkout</a>
</div>

{% else %}
<div>
    <p>Your cart is empty.</p>
</div>
{% endif %}
{% endblock %}