app/product/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField, HiddenField
from wtforms.validators import DataRequired, NumberRange


class AddToBagForm(FlaskForm):
    product_id = HiddenField("Product ID", validators=[DataRequired()], render_kw={'readonly': True})
    quantity = IntegerField("", validators=[DataRequired(), NumberRange(1)], default=1)
    submit = SubmitField("Add to bag")

app/product/__init__.py
from flask import Blueprint

bp = Blueprint("main",__name__)

from app.product import routes

app/product/routes.py
from flask import render_template, current_app, abort, request, g
from app.product import bp
from app.models import Product, Cart, CartItem
from datetime import datetime, timedelta
from flask_login import login_required, current_user
from app import db
from .forms import AddToBagForm


"""@bp.before_app_request
def clear_trailing():
    rp = request.path
    if rp != '/' and rp.endswith('/'):
        return redirect(rp[:-1])"""


@bp.after_app_request
def set_cookie(response):
    cookie = request.cookies
    cart_id = cookie.get("cart")
    if not cart_id:
        if current_user.is_authenticated:
            cart = Cart(current_user.id)
        else:
            cart = Cart()
        db.session.add(cart)
        db.session.flush()
        response.set_cookie("cart", str(cart.id), samesite="Lax", max_age=2592000)
        db.session.commit()
    return response


@bp.before_app_request
def set_cart_count():
    cookie = request.cookies
    cart_id = cookie.get("cart")
    if cart_id:
        cart_count = CartItem.query.filter_by(cart_id=cart_id).count()
        g.cart_count = cart_count



@bp.route("/")
def index():
    products = Product.query.all()
    return render_template("index.html", title="Shoes Shop", products=products)


@bp.route("/collections/womens")
@login_required
def womens():
    products = Product.query.filter_by(gender="F").all()
    return render_template("index.html", title="Women's Shoes", products=products)


@bp.route("/collections/kids")
def kids():
    products = Product.query.filter_by(gender="C").all()
    return render_template("index.html", title="Kid's Shoes", products=products)


@bp.route("/collections/mens")
def mens():
    products = Product.query.filter_by(gender="M").all()
    return render_template("index.html", title="Men's Shoes", products=products)


@bp.route("/collections/womens-new-arrivals")
def womens_new_arrivals():
    to_day = datetime.utcnow()
    new_arrival_date = to_day - timedelta(days=current_app.config["NEW_ARRIVAL_DAYS"])
    products = Product.query.filter_by(gender="F").filter(Product.created_date >= new_arrival_date)
    return render_template("index.html", title="Women's New Arrivals", products=products)


@bp.route("/collections/kids-new-arrivals")
def kids_new_arrivals():
    to_day = datetime.utcnow()
    new_arrival_date = to_day - timedelta(days=current_app.config["NEW_ARRIVAL_DAYS"])
    products = Product.query.filter_by(gender="C").filter(Product.created_date >= new_arrival_date)
    return render_template("index.html", title="Kid's New Arrivals", products=products)


@bp.route("/collections/mens-new-arrivals")
def mens_new_arrivals():
    to_day = datetime.utcnow()
    new_arrival_date = to_day - timedelta(days=current_app.config["NEW_ARRIVAL_DAYS"])
    products = Product.query.filter_by(gender="M").filter(Product.created_date >= new_arrival_date)
    return render_template("index.html", title="Men's New Arrivals", products=products)


@bp.route("/product/<product_name>")
def product_detail(product_name):
    product=Product.query.filter_by(name=product_name).first()
    form = AddToBagForm()
    if not product:
        abort(404)
    form.product_id.data = product.id
    return render_template("product_detail.html", title=product_name, product=product, form=form)

app/templates/_products.html
<table>
    {% for product in products %}
    <tr>
        <td><a href="{{ url_for('main.product_detail', product_name=product.name) }}">{{ product.name }} &ensp;</a></td>
        <td>${{ product.price }}</td>
    </tr>
    {% endfor %}
</table>

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
{% if title %} {{ title }} {% else %}Shoes Shop {% endif %}
{% endblock %}

{% block styles %}
{{ super() }}
    {# <link href="/static/ecommerce.css" rel="stylesheet"> #}
{% endblock %}


{% block body %}

{% block navbar %}
<nav class="navbar navbar-default" role="navigation" >
  <div class="container">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Shoes Shop</a>
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('main.mens') }}">Mens</a></li>
        <li><a href="{{ url_for('main.womens') }}">Womens</a></li>
        <li><a href="{{ url_for('main.kids') }}">Kids</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="{{ url_for('order.shopping_cart') }}">
            Shopping Cart
            {% if g.cart_count %}
            <span class="badge">
              {{ g.cart_count }}
            </span>
            {% endif %}
          </a>
        </li>
        {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('account.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('account.about') }}">My Account</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div> 
</nav>
{% endblock %}

{% block content %}
<div class="container">
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-info" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  {% block app_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% endblock %}

app/templates/bootstrap.html
{% block doc -%}
<!DOCTYPE html>
<html lang="en">
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
<div>
    <span><a href="{{ url_for('main.womens_new_arrivals') }}">Women's New Arrivals</a></span>
    <span>&ensp;&ensp;<a href="{{ url_for('main.mens_new_arrivals') }}">Men's New Arrivals</a></span>
    <span>&ensp;&ensp;<a href="{{ url_for('main.kids_new_arrivals') }}">Kids's New Arrivals</a></span>
</div>
<hr>
<div>
    {% include "_products.html" %}
</div>
{% endblock %}

app/templates/product_detail.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}    
<div class="row">
    <div class="col-md-4">
        <p>Product: {{ product.name }}</p>
        <p>Price: ${{ product.price }}</p>
        <p>{{ product.color }}</p>
        <p>{{ product.size }}</p>
        <form action="/add-to-bag" method="POST">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
</div>
{% endblock %}